server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
logging:
  level:
    org.springframework.cloud: DEBUG